---
title: Open Ownership
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
include:
- _redirects
exclude:
- "*.partial.*"
- "*.map"
show_warnings: false
strict_front_matter: true
disable_disk_cache: true
url: https://www.openownership.org
description: Open Ownership strengthens accountability and advances transparency in
  company ownership
plugins: []
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: true
  transliterated_header_ids: true
  auto_id_prefix: section-
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
highlighter: rouge
colophon: http://www.garethjohnsdesign.com
company: Open Ownership
email: info@openownership.org
tag_manager: GTM-KHKK838
logo: "/assets/img/logo.svg"
placeholder: "/assets/img/placeholder.jpg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  twitter: https://twitter.com/openownership
  github: https://github.com/openownership
pagination:
  enabled: false
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title â€” :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    slugify:
      mode: raw
      cased: true
    layouts:
    - tags.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
imgix:
  source: open-ownership-team.imgix.net
